export type TitleColor =
  | 'mediumBlue'
  | 'darkBlue'
  | 'lightBlue'
  | 'black'
  | 'darkPurple'
  | 'blackYellow'
  | 'opacityBlackYellow'
  | 'umberPeach'
  | 'opacityUmberPeach'
  | 'white'
  | 'coral'
  | 'opacityCoral'
  | 'lightGreen'
  | 'green';
